# -*- coding: utf-8 -*-
"""movie_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vK3N8iS0mo4p9ddkzF4HBkPt11ODiql2
"""

import streamlit as st
import pandas as pd
import pickle

# ---------------------------------------------------------
# Page Config & Setup
# ---------------------------------------------------------
st.set_page_config(page_title="Movie Recommender System", layout="centered")
st.title("Movie Recommender System")

# ---------------------------------------------------------
# Load Precomputed Files (Cached)
# ---------------------------------------------------------
@st.cache_data
def load_data():
    movies_dict = pickle.load(open('movies_dict.pkl', 'rb'))
    movies = pd.DataFrame(movies_dict)
    similarity = pickle.load(open('similarity.pkl', 'rb'))
    return movies, similarity

movies, similarity = load_data()

# ---------------------------------------------------------
# Recommendation Function
# ---------------------------------------------------------
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:10]

    recommended_movies = []
    for i in movies_list:
        recommended_movies.append(movies.iloc[i[0]].title)
    return recommended_movies

# ---------------------------------------------------------
# UI Layout
# ---------------------------------------------------------
selected_movie = st.selectbox(
    "Select or type a movie to get recommendations:",
    movies['title'].values
)

if st.button('Recommend'):
    recommendations = recommend(selected_movie)
    st.subheader(f"Top 9 recommendations for **{selected_movie}**:")

    for idx, rec_movie in enumerate(recommendations, 1):
        st.write(f"{idx}. {rec_movie}")